# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: CharaUTnDT/kernel_build_action@main
        with:
          kernel-url: https://github.com/Deivid21/android_kernel_motorola_sm6225
          kernel-branch: lineage-22.2
          config: vendor/ext_config/guam-default.config
          arch: arm64
          aosp-gcc: false
          aosp-clang: true
          ksu: true
          vendor: motorola
          anykernel3: true
          ksu-version: v0.9.5
          aosp-clang-version: r522817
          disable-lto: true
          bootimg-url: https://sourceforge.net/projects/evolution-x/files/guam/15/boot/boot.img/download
          other-gcc64-url: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-9.3.git
          other-gcc64-branch: lineage-22.2
          other-gcc32-url: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git
          other-gcc32-branch: lineage-19.1
